//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class  Animal 
{
    protected string animalType;
    protected string name;
    protected int age;
    protected decimal cost;
    protected int amountOfFoodPerWeek;
    protected bool adopted;
    protected bool hasAllShots;

	public int Age
    {
        get { return age; }
        set { age = value; }
    }
	public string AnimalType
	{
		get { return animalType; }
		set { animalType = value; }
	}

	public string Name
	{
        get { return name; }
        set { name = value; }
    }

	public decimal Cost
	{
        get { return cost; }
        set { cost = value; }
    }

	public int AmountOfFoodPerWeek
	{
        get { return amountOfFoodPerWeek; }
        set { amountOfFoodPerWeek = value; }
    }

	public bool Adopted
	{
        get { return adopted; }
        set { adopted = value; }
    }

	public bool HasShots
	{
        get { return hasAllShots; }
        set { hasAllShots = value; }
    }

}

