//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Bank
{
    decimal dollarTotal = 0;

    public decimal DollarTotal
    {
        get { return dollarTotal; }
    }
    public void AddToDollarTotal(decimal dollarAmount)
    {
        dollarTotal += dollarAmount;
    }
    public void SubtractFromDollarTotal(decimal dollarAmount)
    {
        dollarTotal -= dollarAmount;
    }


}

