//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cage
{
    int cageNumber;
    bool isOccupied;

    public Cage(int cageNumber)
    {
        this.cageNumber = cageNumber;
    }

    public int CageNumber
    {
        get { return cageNumber; }
        set { cageNumber = value; }
    }
    public bool IsOccupied
    {
        get { return isOccupied; }
        set { isOccupied = value; }
    }

    public void FillCage()
    {
        isOccupied = true;
    }
}

