//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HumaneSociety
{
    List<Animal> animalsList = new List<Animal>();
    List<Adopter> adoptersList = new List<Adopter>();
    List<Cage> cagesList = new List<Cage>();
    Bank bank = new Bank();
    string location; 

    public string Location
    {
        get { return location; }
        set { location = value;  }
    }

    public void AddAnimal()
    {

    }  
    public void DeleteAnimal()
    {

    }  
	public void AddAdopter()
    {

    }
    public void DeleteAdopter()
    {

    }
    public void CreateTotalListOfCages()
    {

    }
    public void DisplayAnimalInformation(Animal animal)
    {

    }
    public void DisplayAdopterInformation(Adopter adopter)
    {

    }
}

